### ISSUE TITLE
Error "Could not load file or assembly Microsoft.TeamFoundation.Common"

### ISSUE THREAD

**Issue by evgenf** [cnsharp/nupack#1]
I clicked "Finish" button in Pack/Deploy window and got the error "Could not load file or assembly 'Microsoft.TeamFoundation.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=<...>".
I use Visual Studio 2017.

**Comment by Bakanych** [comment]
I faced same issue.

**Comment by xunqinbo** [comment]
Sorry,the dll was missing in my previous nuget package and fixed in V1.6.
