### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by lelelic** [cnsharp/nupack#12]
Hi,
I've a project of dll library and a private nuget server.
My AssemblyInfo.cs contains this instructions:
`[assembly: AssemblyVersion("4.1.*")]
[assembly: AssemblyFileVersion("4.1.0.0")]`

but when I deploy the package the version is force to 4.1. How I can to add the numbers of revision and build?
I know I can enter manually but i looking for autofill from build.

Thank you

**Comment by xunqinbo** [comment]
I know what you mean.however,I haven't find a good solution to implement it recently.Maybe later.

**Comment by xunqinbo** [comment]
Dear @lelelic ,this feature has been released in V2.0.1.
