### ISSUE TITLE
IncludeReferencedProjects does not work

### ISSUE THREAD

**Issue by Micha4711** [cnsharp/nupack#15]
The Option IncludeReferencedProjects in the wizard doesn't seem to have any function using NuPack 1.6.3.

I need to set -IncludeReferencedProjects for nuget.exe and checked the box in the wizard, but the output window shows that the builded nuget-command is missing the -IncludeReferencedProjects flag.

A deeper look into DeployWizard.cs shows that chkIncludeReferencedProjects isn't recognized any longer. It seems that the feature was introduced in https://github.com/cnsharp/nupack/commit/30910fe056e88425bfba30ff0aa2f7654541e8dc, which is not longer part of DeployWizard.cs history. Is this a merge/rebase issue? 
However it seems to be lacking in https://github.com/cnsharp/nupack/commit/fecef5e38a116b902a492c4326296558b889b86c.

**Comment by xunqinbo** [comment]
Sorry,there was a merge mistake.has been fixed in V2.0. Thank you!
