### ISSUE TITLE
Official URF Team - Assistance Needed

### ISSUE THREAD

**Issue by lelong37** [cnsharp/nupack#16]
Greetings,

We've tried running the VSIX install, however we are unable to get this working, was wondering if you could help? I'm not sure what's easier, is it possible for you to issue a PR: https://github.com/urfnet/URF.NET? Or just give provide us some guidance. Looks like you have it working already with our solution: https://marketplace.visualstudio.com/items?itemName=CnSharpStudio.NuPack, looks like it's the URF Solution used in your screenshots? Any help, would greatly be appreciated...

I want to say it looks like it can't find dependent nuget packages:

![image](https://user-images.githubusercontent.com/4691404/36823425-b0614b20-1cc2-11e8-9161-fda282ac5964.png)

-Official URF Team
https://github.com/urfnet

**Comment by lelong37** [comment]
Not sure, when you were successful with URF.NET, current structure looks like: https://github.com/urfnet/URF.NET/tree/master/main, just in case if this is helpful, I'm sure you'll be able to see current structure if you are able to quickly clone our repo.

**Comment by xunqinbo** [comment]
Sorry there was a bug in V1.6.3. Would you please try out V2.0? BTW,I was a user of URF.NET,really a great job!Thank you!
