### ISSUE TITLE
Visual Studio 2015 hang when I tried to right click on the solution node in solution explorer with the latest version

### ISSUE THREAD

**Issue by Jimex** [cnsharp/nupack#17]
Visual Studio 2015 hang when I tried to right click on the solution node in solution explorer with the latest version, please solve it, thank you.

![hang](https://user-images.githubusercontent.com/3145858/39170508-69b0cf70-47ce-11e8-966e-460bf6f21dfc.png)

**Comment by jfevia** [comment]
Having the same problem in VS2017. I have temporarily disabled the extension until this is fixed.

**Comment by xunqinbo** [comment]
@Jimex There must have been some special project types not supported well.Can you upload the solution as attachment ?

**Comment by jfevia** [comment]
@xunqinbo in my case, I have several WiX Toolset projects. That seems to be the case in the screenshot as well.

**Comment by Jimex** [comment]
@jfevia @xunqinbo Yea, same, I also have 2 WIX projects in my solution.

**Comment by xunqinbo** [comment]
Fixed in V2.0.2,closing for now - feel free to re-open if it needs further discussion.
