### ISSUE TITLE
Double slash in nuget push

### ISSUE THREAD

**Issue by paul-charlton** [cnsharp/nupack#19]
Hi,
When I run this Deploy from a .NetStandard 2 class library i get a "File does not exist" error as the utility seems to be putting a double slash in the nuget output directory, ie "\\bin\\Nuget\\".  From the output window with path (obscured my running directory):

C:\WINDOWS\system32>"C:\Program Files (x86)\NuGet\nuget.exe" push "C:\vs\[PROJECTPATH]\\\\bin\NuGet\\\\[PROJECTNAME].nupkg" -source [NUGETSERVER]
File does not exist (C:\vs\[PROJECTPATH]\\\\bin\NuGet\\\\[PROJECTNAME].nupkg).

Paul.

**Comment by lciocci** [comment]
Just to add - I have the same issue. Is there some workaround for this?

[Edit] This is for Visual Studio 2017, version 2.0.3.

Command:
"C:\NuGet\nuget.exe" push "C:\Users\[user]\source\repos\TestNuGetDeploy\\\bin\NuGet\\\TestNuGetDeploy.1.0.0.nupkg" -source [private NuGet url] [API key] 

Error:
File does not exist (C:\Users\[user]\source\repos\TestNuGetDeploy\\\bin\NuGet\\\TestNuGetDeploy.1.0.0.nupkg).

**Comment by xunqinbo** [comment]
This bug is related to  #20 ,reopened after solved that one.
Would be fixed in V2.0.4.

**Comment by paul-charlton** [comment]
Hi,
I'm now running v2.0.4 but getting the exact same error?

"\\\\bin\Nuget\\\\[PACKAGE NAME].nupkg"

Paul.

**Comment by xunqinbo** [comment]
@paul-charlton  Sorry,there was a merge mistake.I have published V2.0.5.Please try it later.

**Comment by xunqinbo** [comment]
Any update on the issue? closing for now . feel free to re-open if it needs further discussion.

**Comment by paul-charlton** [comment]
Yeah, it runs without the double slash now.
