### ISSUE TITLE
New extension release does not allow for deployment to server

### ISSUE THREAD

**Issue by lewis267** [cnsharp/nupack#20]
I have version 1.6.3 of NuPack installed in my Visual Studio Professional 2017 IDE and I use it regularly to deploy nuget packages to a server in our local network by supplying an ip address.

During the **Pack Settings** step of deployment I supply a **Package Output directory:** as `\\<ip-address>\<nuget-folder>`.

Next during the **Deploy** step I specify the **NuGet Server:** as `<ip-address>`.

As I said, this works perfectly with version 1.6.3.

---
Now my friend is trying to deploy in the _exact_ same manner with the most current version of __NuPack__ v.2.0.1 and the tool is placing the NuGet package in a generated folder at `C:\\<ip-address>\<nuget-folder>`, which is on the local machine.

This seems like a bug to me and keeps us from being able to use the tool successfully.

**Comment by xunqinbo** [comment]
Sorry,we haven't this use case before,I'll fix it in V2.0.2.

**Comment by xunqinbo** [comment]
Any update on the issue? closing for now . feel free to re-open if it needs further discussion.

**Comment by lewis267** [comment]
Issue is fixed in current release! Thanks!
