### ISSUE TITLE
Nuget server path with spaces not working.

### ISSUE THREAD

**Issue by AlainDupont** [cnsharp/nupack#21]
Passing this path \\ekhosoftdc\ekhosoft\Power Factor\Nuget\packages to the NuGet Server in Deploy window does push the package to the server.

C:\Windows\system32>"C:\NuGet\nuget.exe" push "C:\GitRepo\energy-unittest-utilities\PowerFactors.Energy.NUnitHelper\bin\NuGet\PowerFactors.Energy.NUnitHelper.1.0.1.nupkg" -source \\ekhosoftdc\ekhosoft\Power Factor\Nuget\packages 
Pushing PowerFactors.Energy.NUnitHelper.1.0.1.nupkg to '\\ekhosoftdc\ekhosoft\Power'...
Could not find a part of the path '\\ekhosoftdc\ekhosoft\Power\PowerFactors.Energy.NUnitHelper.1.0.1.nupkg'.

**Comment by xunqinbo** [comment]
nuget source should be a http site.

**Comment by AlainDupont** [comment]
It is not a http server. It is a local driver such as c:\nuget\packages for us\

**Comment by xunqinbo** [comment]
I see.It should be quoted and released in V2.0.6.Thank you!
