### ISSUE TITLE
VSSharp not found

### ISSUE THREAD

**Issue by dreammaster38** [cnsharp/nupack#24]
I tried to create the file 'package.nuspec'. I right clicked on my project --> Add --> package.nuspec.
Unfortunately NuPack presented the following error message to me:

![image](https://user-images.githubusercontent.com/834612/44096161-ec46e776-9fda-11e8-9fdd-630425af3ae7.png)

It cannot find VsSharp package or its dependencies. Nevertheless there is a version 1.3.2 of VsSharp in the extension dir.

**Comment by agarcian** [comment]
Experiencing the same issue...

**Comment by xunqinbo** [comment]
There was a dependency problem.It should has been set as BindingRedirect.Fixed in V2.1.1.
