### ISSUE TITLE
Support for VS2019

### ISSUE THREAD

**Issue by maratbakirov** [cnsharp/nupack#26]
Could it be possible to support Visual Studio 2019?
thank you!

**Comment by xunqinbo** [comment]
Maybe after RC released.

**Comment by maratbakirov** [comment]
thank you very much! looking forward to it ...

**Comment by penCsharpener** [comment]
VS2019 ist out now. I'd also really like this in 2019

**Comment by MJTAG** [comment]
Yes VS 2019 support would be great

**Comment by penCsharpener** [comment]
It looks like it's already there. I installed it yesterday for vs2019!

**Comment by xunqinbo** [comment]
Sorry for late,everyone. I released version 3.0 two weeks ago. Feel free to re-open if it needs further discussion.
