### ISSUE TITLE
developmentDependency false when using Fody

### ISSUE THREAD

**Issue by Stumpii** [cnsharp/nupack#3]
Have a project with Fody which in packages.config is configured developmentDependency=true. Nupack is including the file in dependencies with developmentDependency=false. This not seem right as it does not need to be included. Also nuget 4.1 pack fails complaining that 'The 'developmentDependency' attribute is not declared.'

Any ideas?

Steve

**Comment by Stumpii** [comment]
Appears the issue is that nupack is including the dependencies in the nuspec file but shouldn't. Manually deleting those lines results in the package being created successfully.

**Comment by xunqinbo** [comment]
The previous versions didn't support developmentDependency attribute.The issue was fixed in V1.6.
