### ISSUE TITLE
Problem with developmentDependecy Tag

### ISSUE THREAD

**Issue by martindafonte** [cnsharp/nupack#7]
Hi, I'm having a problem with the generated nuspec file.
The extension automatically adds a developmentDependecy Tag on every dependency element. The problem is that the nuget command doesn't recognize this attribute, and so it doesn't create the package.

The workaround is to manually delete the attribute every time you want to publish a package and run the nuget commands by hand, but then, it makes no sense to use the extension.

Here is an image of the tags I'm talking about
![image](https://user-images.githubusercontent.com/13356673/29028557-13f83e28-7b5b-11e7-8ba2-bb6639523b0f.png)

I downloaded the code and managed to fix the problem deleting the DevelopmentDependency property on the Dependency class (src/NuGet/Package.cs line 110)

Regards

**Comment by xunqinbo** [comment]
Thank you for your feedback,Martin.This problem has been fixed in V1.6.2.
