### ISSUE TITLE
ISSUE DEPLOYING USING NUGET

### ISSUE THREAD

**Issue by KunleSmart** [cnsharp/nupack#8]
I encounter error message:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE>The 'developmentDependency' attribute is not declared.
Microsoft Windows [Version 10.0.15063]

this happend once in a while i try to deploy to Nuget. The error prevents me from deploying the library to nuget until the project is recreated from start. This has happened so many times.

**Comment by xunqinbo** [comment]
Thank you for your feedback,Kunle.This problem is the same as issue #7 , and has been fixed in V1.6.2.
